NAVIGATE_BACK_ALT_LIST = [
    "Back",
    "back",
    "BACK",
    "Back Button",
    "Back button",
    "back button",
    "Back Icon",
    "Back icon",
    "Back Arrow",
    "Back arrow",
    "arrow back",
    "Image Back Arrow",
    "Toolbar back arrow",
    "back navigation icon",
    "back-button",
    "back_button",
    "backButton",
    "backBtn",
    "backbutton",
    "BackButton",
    "btnBack",
    "btn_back",
    "btnNavigateBack",
    "aqa_navigation_back",
    "login.arrowback",
    "ArrowBack",
    "backArrow",
    "backIcon",
    "map_back_button",
    "Toolbar_Img_Back",
    "CustomNavBar_BackButton",
    "CustomNavBar_BackButtonImage",
    "bar-back-android",
    "to_pageBack",
    "onBack",
    "IABackButton",
    "Navigate up",
    "Navigate Up",
    "navigate up",
    "nagivate up",
    "Navigate up button",
    "Navigate back",
    "Navigate Back",
    "navigate back",
    "Navigation Back",
    "Navigate up, go back",
    "Go back",
    "Go Back",
    "go back",
    "GO BACK",
    "Go back.",
    "Go back. Button.",
    "Go back to previous screen",
    "Return back",
    "Back, Navigates to the previous screen",
    "Go back, Navigates to the previous screen",
    "返回",
    "返回按钮",
    "返回上一级",
    "前に戻る",
    "戻る",
    "Назад",
    "Вернуться назад",
    "Atrás",
    "Botón atrás",
    "Voltar",
    "Volver atrás",
    "Indietro",
    "Torna indietro",
    "Terug",
    "Geri",
    "رجوع",
    "Retour",
    "RETOUR",
    "retour",
    "Zurück",
    "zurück",
]
